version: '3'

services:


  # MySQL database service
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: nayab
      MYSQL_PASSWORD: wordpress
     ports:
      - '8081:80'
    networks:
      - wp_network
    volumes:
      - ./db_data:/var/lib/mysql
        # WordPress service
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: nayab
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - '8080:80'
    networks:
      - wp_network
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
networks:
  wp_network:
    driver: bridge
