# Use the official MySQL image as the base image
FROM mysql:latest

# Environment variables for configuring MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=wordpress
ENV MYSQL_USER=wordpress
ENV MYSQL_PASSWORD=wordpress

# Expose port 3306 for MySQL
EXPOSE 3306

# Start MySQL server
CMD ["mysqld"]

